// GENERATED by scripts/extract_presets.py — do not edit by hand.
// Source: upstream presets/*.vstpreset, component state = kNumParams float32s
// (19 in these presets; params 19-21 postdate them and use Param.defaultValue).
//
// These are upstream's own six factory patches (Dorje, Jamyang, Monastary,
// Ngawang, Rabten, Tinley) — kept here as provenance/source data, NOT as a
// user- or host-facing preset list any more. `MonkSynthAU.factoryPresets`
// stopped exposing these names directly (see that file's "Factory presets"
// section): nothing in the app surfaces them today. Instead, each patch
// became the voice of one of MonkSynth's six new characters (Dog, Ghost,
// Fire Fighter, Punk, Pizza, Cat) via `FactoryVoiceTable`, which reads these
// arrays verbatim. Still very much load-bearing — do not delete this file as
// unused just because nothing named "Dorje" et al. shows up in the UI or the
// AU's preset list any more.
import AVFoundation

struct Preset {
    let name: String
    let values: [AUValue]
}

let kFactoryPresets: [Preset] = [
    Preset(name: "Dorje", values: [0.400000, 0.500000, 0.300000, 0.000000, 0.000000, 0.500000, 0.500000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.500000, 1.000000, 0.000000, 0.000000, 0.500000, 0.500000, 0.500000, 0.000000, 0.500000]),
    Preset(name: "Jamyang", values: [0.500000, 0.500000, 0.000000, 0.750000, 0.000000, 0.500000, 0.500000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.500000, 1.000000, 0.000000, 0.000000, 0.500000, 0.500000, 0.500000, 0.000000, 0.500000]),
    Preset(name: "Monastary", values: [0.400000, 0.445236, 0.300000, 0.000000, 0.094488, 0.500000, 0.034247, 0.109589, 0.000000, 1.000000, 0.041096, 0.264840, 0.465753, 0.335616, 1.000000, 0.178082, 0.000000, 0.500000, 0.500000, 0.500000, 0.000000, 0.500000]),
    Preset(name: "Ngawang", values: [0.800000, 0.500000, 0.600000, 0.250000, 0.000000, 0.500000, 0.500000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.500000, 1.000000, 0.000000, 0.000000, 0.500000, 0.500000, 0.500000, 0.000000, 0.500000]),
    Preset(name: "Rabten", values: [0.500000, 0.500000, 0.800000, 0.500000, 0.000000, 0.500000, 0.500000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.500000, 1.000000, 0.000000, 0.000000, 0.500000, 0.500000, 0.500000, 0.000000, 0.500000]),
    Preset(name: "Tinley", values: [1.000000, 0.500000, 0.900000, 1.000000, 0.000000, 0.500000, 0.500000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.500000, 1.000000, 0.000000, 0.000000, 0.500000, 0.500000, 0.500000, 0.000000, 0.500000]),
]
