#!/usr/bin/env python3
"""Extract MonkSynth factory presets from upstream .vstpreset files.

Upstream Processor::getState (cpp/src/processor.cpp:103-110) writes state as
a bare sequence of kNumParams little-endian float32s, written directly to
the component's IBStream. In the .vstpreset container that blob lives in
the 'Comp' chunk referenced by the trailing 'List' chunk.

.vstpreset binary layout (reverse-engineered from the shipped presets with
struct.unpack_from against hard offsets, cross-checked by locating the
literal b"List"/b"Comp" text in the file and confirming it lines up with
the offsets read out of the header/list — see the bottom of this docstring
for the values that were checked):

    offset  size  field
    0       4     magic 'VST3'
    4       4     int32 version
    8       32    ASCII-hex class ID (FUID as 32 hex chars)
    40      8     int64 offset of the 'List' chunk   <-- NOT byte 44

  'List' chunk (at the offset read above):
    +0      4     chunk id 'List'
    +4      4     int32 entry count                  <-- no version field here
    +8      20*n  entries, each:
                     4   chunk id (e.g. 'Comp', 'Cont', 'Info')
                     8   int64 offset (absolute, from file start)
                     8   int64 size (bytes)

An earlier draft of this script assumed the list offset lived at byte 44
and that the List header was id+version+count (12 bytes). Both were wrong:
reading byte 40 and treating the List header as id+count (8 bytes) is what
makes the decoded chunk table's byte ranges actually line up with where
"List"/"Comp" appear in the file (confirmed for all six presets: Dorje,
Jamyang, Ngawang, Rabten, Tinley all resolve to List at 124 / Comp at
[48,124); Monastary — the one preset with extra Cont/Info chunks and a
metadata XML blob — resolves to List at 763 / Comp at [48,124) too).

The 'Comp' entry's [offset, offset+size) range holds the raw float32 blob
written by Processor::getState. In all six shipped presets this blob is 19
floats (76 bytes) — one parameter short of the current kNumParams=22.
kNumParams grew after these presets were exported, adding pitchBend,
pitchBendRouting, and pitchWheelRaw (indices 19-21). This is a real-world
instance of the "short state" case Processor::setState already handles
(processor.cpp:112-127): trailing values not present in the blob are left
at their defaults rather than guessed at.

Usage: scripts/extract_presets.py [../monksynth-upstream/presets]
"""
import struct
import sys
from pathlib import Path

NUM_PARAMS = 22
ORDER = ["Dorje", "Jamyang", "Monastary", "Ngawang", "Rabten", "Tinley"]


def read_component_state(path: Path) -> list:
    data = path.read_bytes()
    if data[:4] != b"VST3":
        raise ValueError(f"{path.name}: not a VST3 preset")
    (list_offset,) = struct.unpack_from("<q", data, 40)
    (chunk_id, count) = struct.unpack_from("<4si", data, list_offset)
    if chunk_id != b"List":
        raise ValueError(
            f"{path.name}: expected List chunk at {list_offset}, got {chunk_id!r}"
        )
    entry = list_offset + 8
    for _ in range(count):
        (cid, offset, size) = struct.unpack_from("<4sqq", data, entry)
        entry += 20
        if cid == b"Comp":
            n = min(NUM_PARAMS, size // 4)
            values = list(struct.unpack_from(f"<{n}f", data, offset))
            values += [None] * (NUM_PARAMS - n)
            return values
    raise ValueError(f"{path.name}: no Comp chunk")


def main() -> int:
    default_src = Path(__file__).resolve().parent.parent.parent / "monksynth-upstream" / "presets"
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else default_src

    # Params 19-21 (pitchBend, pitchBendRouting, pitchWheelRaw) postdate these
    # presets' export, so they are always missing (None) from the extracted
    # blob; fall back to Param.defaultValue (AU/Params.swift), reproduced here.
    defaults = [0.5, 0.5, 0.8, 0.5, 0.0, 0.5, 0.5, 0.0, 0.0, 1.0, 0.0,
                0.0, 0.0, 0.5, 1.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.0, 0.5]
    assert len(defaults) == NUM_PARAMS

    rows = []
    for name in ORDER:
        values = read_component_state(src / f"{name}.vstpreset")
        for v in values:
            if v is not None:
                assert 0.0 <= v <= 1.0, f"{name}: value {v} out of [0,1]"
        values = [d if v is None else v for v, d in zip(values, defaults)]
        body = ", ".join(f"{v:.6f}" for v in values)
        rows.append(f'    Preset(name: "{name}", values: [{body}]),')

    out = Path(__file__).resolve().parent.parent / "AU" / "FactoryPresets.swift"
    out.write_text(
        "// GENERATED by scripts/extract_presets.py — do not edit by hand.\n"
        "// Source: upstream presets/*.vstpreset, component state = kNumParams float32s\n"
        "// (19 in these presets; params 19-21 postdate them and use Param.defaultValue).\n"
        "import AVFoundation\n\n"
        "struct Preset {\n"
        "    let name: String\n"
        "    let values: [AUValue]\n"
        "}\n\n"
        "let kFactoryPresets: [Preset] = [\n" + "\n".join(rows) + "\n]\n"
    )
    print(f"wrote {out} with {len(rows)} presets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
